### ISSUE TITLE
Cannot create Branch at web page.  Am I doing something wrong?  

### ISSUE THREAD

**Issue by thatlostboy** [githubschool/apr-09#17] opened 2018-04-10 17:29 UTC
![screenshot](https://user-images.githubusercontent.com/12224967/38573104-ebc464ca-3ca9-11e8-868a-c95d42bf34b8.jpg)

**Comment by a-a-ron** [comment] 2018-04-10 17:32
Hey @thatlostboy, are you signed in?

**Comment by thatlostboy** [comment] 2018-04-10 17:38
Yes,  am logged in.

**Comment by a-a-ron** [comment] 2018-04-10 17:51
Looks like you needed to accept your invitation to be a collaborator. Confirmed through Zoom chat so closing issue. Re-open if you're still experiencing issues. Thanks!

**Closed by a-a-ron** 2018-04-10 17:51 UTC
